apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adam-facade
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  rules:
  - host: adam.financial
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-project-phoenix
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adam-facade-legacy
spec:
  rules:
  - host: adam.financial
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adam-monolith
            port:
              number: 8080
